---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adbir
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: registry.wuhoo.xyz/jerry/adbir
              tag: v0.2.0-dashboard-icons
            env:
              OUT_DIR: /public
              CONFIG_PATH: /config/config.yaml
            lifecycle:
              postStart:
                exec:
                  command:
                  - "/bin/sh"
                  - "-c"
                  - "wget https://files.catbox.moe/ujwnph.webp -O /public/logo.webp"
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: adbir.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: adbir.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: configMap
        name: adbir-config
    configMaps:
      config:
        data:
          config.yaml: |-
            title: "wuhoo!"
            image: "logo.webp"

            services:
              - name: "Federated"
                items:
                  - name: "Element"
                    logo: "/icons/svg/element.svg"
                    subtitle: "Federated, E2EE messaging"
                    url: "https://element.${DOMAIN}"
                  - name: "Cinny"
                    logo: "/icons/svg/cinny.svg"
                    subtitle: "Yet another Matrix client"
                    url: "https://cinny.${DOMAIN}"
                  - name: "Matrix Synapse"
                    logo: "/icons/svg/matrix-synapse.svg"
                    subtitle: "Federated protocol"
                    url: "https://matrix.${DOMAIN}/_matrix/static/"
                  - name: "Matrix Federation Tester"
                    logo: "/icons/svg/matrix.svg"
                    subtitle: "Tool to test Matrix federation"
                    url: "https://federationtester.${DOMAIN}"
              - name: "Media"
                items:
                  - name: "Jellyfin"
                    logo: "/icons/svg/jellyfin.svg"
                    subtitle: "Media streaming server"
                    url: "https://jellyfin.${DOMAIN}"
                  - name: "Jellyfin Vue"
                    logo: "/icons/png/jellyfin-vue.png"
                    subtitle: "Alternative Jellyfin frontend"
                    url: "https://jf-vue.${DOMAIN}"
                  - name: "Jellyseerr"
                    logo: "/icons/svg/jellyseerr.svg"
                    subtitle: "Media request service"
                    url: "https://jellyseerr.${DOMAIN}"
                  - name: "Feishin"
                    logo: "/icons/png/feishin.png"
                    subtitle: "Music client for Jellyfin"
                    url: "https://feishin.${DOMAIN}"
              - name: "Cloud services"
                items:
                  - name: "GitLab"
                    logo: "/icons/svg/gitlab.svg"
                    subtitle: "GitLab instance"
                    url: "https://gitlab.${DOMAIN}/explore/"
                  - name: "Nextcloud"
                    logo: "/icons/svg/nextcloud.svg"
                    subtitle: "File share and collaboration platform"
                    url: "https://cloud.${DOMAIN}"
                  - name: "Vaultwarden"
                    logo: "/icons/svg/bitwarden.svg"
                    subtitle: "Password manager"
                    url: "https://vaultwarden.${DOMAIN}"
                  - name: "Immich"
                    logo: "/icons/svg/immich.svg"
                    subtitle: "Self-hosted photo and video backup solution"
                    url: "https://photos.${DOMAIN}"
                  - name: "Paperless-ngx"
                    logo: "/icons/svg/paperless.svg"
                    subtitle: "Scan, index, and archive physical documents"
                    url: "https://paperless.${DOMAIN}"
                  - name: "FindMyDevice (FMD)"
                    logo: "https://gitlab.com/Nulide/findmydevice/-/raw/master/FMD.svg"
                    subtitle: "Track lost devices"
                    url: "https://fmd.${DOMAIN}"
                  - name: "Send"
                    logo: "/icons/svg/firefox-send.svg"
                    subtitle: "Client-side encrypted file sharing"
                    url: "https://send.${DOMAIN}"
                  - name: "Privatebin"
                    logo: "/icons/svg/privatebin.svg"
                    subtitle: "Zero-knowledge encrypted pastebin"
                    url: "https://paste.${DOMAIN}"
              - name: "Misc"
                items:
                  - name: "Authentik"
                    logo: "/icons/png/authentik.png"
                    subtitle: "Identity Provider and Single Sign-On"
                    url: "https://auth.${DOMAIN}"
                  - name: "Ntfy"
                    logo: "/icons/svg/ntfy.svg"
                    subtitle: "Push notifications"
                    url: "https://ntfy.${DOMAIN}"
                  - name: "Uptime.rs"
                    logo: "/icons/svg/uptime-kuma.svg"
                    subtitle: "Uptime monitoring"
                    url: "https://uptimers.${DOMAIN}"
                  - name: "Librespeed"
                    logo: "/icons/svg/librespeed.svg"
                    subtitle: "Internet speedtest"
                    url: "https://speedtest.${DOMAIN}"
                  - name: "Wiki"
                    logo: "/icons/png/wikijs.png"
                    subtitle: "wiki.js instance"
                    url: "https://wiki.${DOMAIN}"
                  - name: "Hat.sh"
                    logo: "/icons/svg/hatsh.svg"
                    subtitle: "Simple, fast, secure client-side file encryption"
                    url: "https://hatsh.${DOMAIN}"
                  - name: "Arch Linux mirror"
                    logo: "/icons/svg/files.svg"
                    subtitle: "Arch Linux repositories mirror"
                    url: "https://mirror.${DOMAIN}"
                  - name: "AUR packages"
                    logo: "/icons/svg/files.svg"
                    subtitle: "Repository for packages built from AUR"
                    url: "https://aur.${DOMAIN}"
                  - name: "A Dark Room"
                    logo: "/icons/svg/firewalla.svg"
                    subtitle: "A minimalist text adventure"
                    url: "https://adarkroom.${DOMAIN}"
              - name: "Downloads"
                items:
                  - name: "Sonarr (Internal)"
                    logo: "/icons/svg/sonarr.svg"
                    subtitle: "TV series PVR system"
                    url: "https://sonarr.${DOMAIN}"
                  - name: "Sonarr (4k) (Internal)"
                    logo: "/icons/svg/sonarr.svg"
                    subtitle: "TV series PVR system"
                    url: "https://sonarr4.${DOMAIN}"
                  - name: "Radarr (Internal)"
                    logo: "/icons/svg/radarr.svg"
                    subtitle: "Movies PVR system"
                    url: "https://radarr.${DOMAIN}"
                  - name: "Radarr (4k) (Internal)"
                    logo: "/icons/svg/radarr.svg"
                    subtitle: "Movies PVR system"
                    url: "https://radarr4.${DOMAIN}"
                  - name: "Prowlarr (Internal)"
                    logo: "/icons/svg/prowlarr.svg"
                    subtitle: "Indexers"
                    url: "https://prowlarr.${DOMAIN}"
                  - name: "qBittorrent (Internal)"
                    logo: "/icons/svg/qbittorrent.svg"
                    subtitle: "P2P torrent client"
                    url: "https://torrent.${DOMAIN}"
              - name: "Management"
                items:
                  - name: "Proxmox VE (Internal)"
                    logo: "/icons/svg/proxmox.svg"
                    subtitle: "Proxmox Virtual Environment web management"
                    url: "https://pve.${DOMAIN}"
                  - name: "OPNsense (Internal)"
                    logo: "/icons/svg/opnsense.svg"
                    subtitle: "Open-source firewall"
                    url: "https://kizu.${DOMAIN}:8443"
                  - name: "Ceph Dashboard (Internal)"
                    logo: "/icons/svg/ceph.svg"
                    subtitle: "Distributed object, block, and file storage platform"
                    url: "https://10.40.0.30:8443/"
                  - name: "Grafana (Internal)"
                    logo: "/icons/svg/grafana.svg"
                    subtitle: "Data visualization platform"
                    url: "https://grafana.${DOMAIN}"
