---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: collabora-code
      sourceRef:
        kind: HelmRepository
        name: chrisingenhaag
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: nextcloud-secret
    valuesKey: COLLABORA_PASSWORD
    targetPath: collabora.password
  values:
    image:
      repository: docker.io/collabora/code
      tag: 25.04.1.1.1
    collabora:
      aliasgroups:
      - domain: https://cloud.${DOMAIN}:443
      dictionaries: en_US
      extra_params: --o:ssl.termination=true --o:ssl.enable=false
      server_name: collabora\.${DOMAIN_ESCAPED}
      username: admin
    ingress:
      annotations:
        homelab/public: "true"
        external-dns.alpha.kubernetes.io/hostname: collabora.${DOMAIN}
        external-dns.alpha.kubernetes.io/target: ${DOMAIN}
      enabled: true
      className: nginx-public
      hosts:
      - collabora.${DOMAIN}
      paths:
      - /
