---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nextcloud-postgres-cluster
  annotations:
    k8up.io/backup: "false"
spec:
  teamId: "nextcloud"
  volume:
    size: 10Gi
  numberOfInstances: 1
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: "1"
      memory: 500Mi
  users:
    # database owner
    nextcloud:
    - superuser
    - createdb
  databases:
    nextcloud: nextcloud
  postgresql:
    version: "17"
