apiVersion: v1
kind: Secret
metadata:
    name: kured-config
    namespace: kube-system
stringData:
    values.yaml: ENC[AES256_GCM,data:aGtDuYzMJ1QztrFkzJ1gKhxJ6DhodE9nkSMfb8sTs/mMJa6U4PwoHvUxSrESwEwEWj8if5rJtvWoc74JiT00n8t2QyxLS8K390qLwpSznHKoLlDtd1COLw9vBI6ijmezlXNypyMQk6F6Hmwnp+4TvgI=,iv:LQMIefiRqPmwtw9xfGb6FK811vgozICSLQt8KJtwm14=,tag:vYCWCDiW75VIxRotU0yfFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWRQMDE2cmZjVzZmTlRs
            VFlYNGtBTkRUeERTUUVVM3dkUFNNSjgxTDJjCngzVkx2QjMxRUtzakI4aXZFSEhC
            eWllcXhQa3VvYklPcmZIZ2JUM0VsblUKLS0tIElzWHVVSThSTFF2UTBvbEhPalZw
            UFRlbTBZN0cxcTIxZGIzamxDclBnTzAK/k1bW2k6nO6xh6qFNH28xpNBJ85hfUrm
            Ziw4i2DJMVcyJakE5iWTKHkqUJw1xRJafYERGTdWKfd3dJ6gfAcMag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T05:00:15Z"
    mac: ENC[AES256_GCM,data:lzv7Pwjp4QyUA2bTShBHvydjAOsvAJqm6XOVK4tEt6kIucW9LcGOjOyvO6vS7G6ss1JfDEeRhsB5sKBxsWMoCvMq24rdsvtaFfBz8ly86u0KUoTPXUesg6XoirURY6ECPie8RXuuXvuC9GNZRxDg/05KctZ2+eTBOJwUEgvbtck=,iv:7BVbdY8fqRdapjkcQBFLBVGr1r9stovuvHZ4bRcWV/4=,tag:aTHFC1b+Agc5ZfX1TCM3CA==,type:str]
    version: 3.13.3
