---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coturn
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/instance: coturn
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coturn
      app.kubernetes.io/instance: coturn
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coturn
        app.kubernetes.io/instance: coturn
        app.kubernetes.io/version: 0.0.1
    spec:
      hostNetwork: true
      containers:
      - name: coturn
        image: quay.io/coturn/coturn:4.7.0-alpine
        imagePullPolicy: Always
        volumeMounts:
        - name: coturn-config
          mountPath: /etc/coturn/turnserver.conf
          subPath: turnserver.conf
          readOnly: true
        ports:
        - name: turn-port1
          containerPort: 3478
          hostPort: 3478
          protocol: UDP
        - name: turn-port2
          containerPort: 3478
          hostPort: 3478
          protocol: TCP
        args:
        - -v
      volumes:
        - name: coturn-config
          secret:
            secretName: coturn-secret
            option: false
