apiVersion: v1
kind: Secret
metadata:
    name: firefox-syncstorage-rs-secret
    namespace: firefox-syncstorage-rs
stringData:
    SYNC_MASTER_SECRET: ENC[AES256_GCM,data:V71jD27gSmPQaaedzyBx+n7pHkPRk2pjJlLWDAFBSxmT9NuO2MC+GKA1NdZ+yfW4DUzbf/4gBnyqvdaYQqUjZw==,iv:ScrvlZNiwWCDQ6s8z8zwrCsx/mGTmaDHRxQzCiLb56I=,tag:zL163Gha2tGEi7Sz/XIWaw==,type:str]
    SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET: ENC[AES256_GCM,data:X8X3iMAgEWUFQJBYGCiyYx+tZYJygmorkmFy/nZdlRSbqbJz41RQAs7f3RSpH/f5llotRK/c33Z3a8vfxjXL/w==,iv:MDKf0SbCarR4aMi4LczkgeFzPdk4VaG7CTqqVYJzfUc=,tag:1C8pHDFNV+NoDGThc6ty5w==,type:str]
    SYNC_SYNCSTORAGE__DATABASE_URL: ENC[AES256_GCM,data:2WjhugxwvUi32lXgTJUX/+Aj9DJD1Hm+oHx0TItSwsKovr7EorYEwphU3+jJjkLIih8hWRe2Lw+XjSHo66pNhPZk8Asfv7MTP+l/WzX8TQus+XSvYdqBd3Wcuq3/KmJjLBAkyTtY8c3AlPuMj/6Cw39XL/oOCfeEKlqc,iv:/kb5JjUjI3swFJHctzq17XFzfiSP7PtBlQNFmvu0XQA=,tag:kPTB4gv64SvGMe8gTUTYAA==,type:str]
    SYNC_TOKENSERVER__DATABASE_URL: ENC[AES256_GCM,data:vG9UJE/kN2cqa+NWAX6htIbEt5YSTC98geo1Parzg2T10MQANW7W3+tQ1HVzrGeTKBToUGQQMnnTFUVPQh+jlhCzDHdepg3jt7f6JVi3YEBfDVRn60U5HhLaD1Kcj6ALHrFF1qq/glxCO7lGzoVuGJzMnYkAyi9QvURp,iv:CQDI/AmSmlnv3s9nbXt3kfAR3o6YuqtpgpirZs2DlvM=,tag:DMVzZ3q43k6a+e0Uj62LCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRkNhSDY1UTErU2NpNHhN
            RHJxNUZsM3NxU1B3enhmckRENWhFaSswbnp3CmxvQTAyWk1zdFEyMElYK2wwdE5m
            aGZuQ3ZwMFphMWorTjBrUXE4c3BJbmcKLS0tIGE3dUtBZmF1QUpXS2kveW55dGM1
            b0ljZEFOZTlTbm1UM0pjcHNuV2gwbVUK4rvf7bnaosEGYzNX4FNAkFNvF3v9vl0/
            BJN/cyYtn96CaW7S3jcFVxSTkxGy0mpFKnpHgjkkdjZacvW5pPaXSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T04:15:30Z"
    mac: ENC[AES256_GCM,data:adSCXHbOaDrxHWWprfuXi4yeJjLHZIp2zW+AjlDZdl2ydHL84WT7puTMSVutKaaZwGwkolmNibpVxhXo9yeRaLfl4kfhP+IrRnD4bRSkjiWpmF/ykPWGMy8Qe0rop9CbxFKEGeAHrvjWxrRtql/78zLx19LqPVNCACc+B0rlgIo=,iv:bfjl2LzywI5gemin0AoLxrwEKGfn4olztxwgI+WgQyE=,tag:XkMfHhO3lKp7B3c8dK2k4Q==,type:str]
    version: 3.13.3
