apiVersion: v1
kind: Secret
metadata:
    name: syncstorage.firefox-syncstorage-rs-postgres-cluster.credentials.postgresql.acid.zalan.do
    namespace: firefox-syncstorage-rs
stringData:
    username: ENC[AES256_GCM,data:6h/tftYXptLxj5E=,iv:B0g1ALMCTBfC/X7mmwfYAFMCX4aQ2z5ExP113X3dnYs=,tag:ifiwiuCT2CimP2qIUvo+Qw==,type:str]
    password: ENC[AES256_GCM,data:ujPQ/6lSqzfkQ2HlWlDYjamcDI3x0UycfMFOSRtzZy8SKyEGVYpAQBpG+kFu28yc,iv:rFgg3SFKDOGDkeNp6HCCp1uUK7xrEE7PTltJD9ofMS4=,tag:yfuO5EjHOWVgVw8rBea9yA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aE5ySWhCcm9CeEdlVXFq
            SG93c1F2dWlPWW5WUWF2U0JjYWJpcml3aTN3CmVBU3JOYUxPcEVQUnFlcmZ6Y2hH
            K21aajVOTjlMWENIYVltSDR3U1dvMTgKLS0tIGVud2tVbmFHMFNpejFTYUpwUDBG
            UkNENURvRnZzOUNuVTRQQnBMZ2sxUXMKEiwqCJ1rjUUV6GB5VGHZvntCPXnInToP
            VX+JTFJDOP1HzGIa/JWz8N9uFiL7Qlb/cEuvIYXSpBmTZ0AEZrBDUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T04:15:30Z"
    mac: ENC[AES256_GCM,data:tWAPjP0y0jVVf6lkgld5dwIyHtEM91E8RfFEtIdkgAag/3The2mkFEJNYU3KF+NLQYh8KS2DyT0gxtDRBYHlW7SNMkNZhzgW5Pcp6fxlUwoU2tLnk+iW+jMr93o5ndHZ2GDKRFLjPOoF2goKB+07xsq0Ny8DC6CZMnkErnzmNww=,iv:qqBTzfafvHeOGmSnFm+p0q6Yn5RXneqwKAID/bTaLrI=,tag:B0DNiaM7VFUoLztSnn7L4Q==,type:str]
    version: 3.13.3
