apiVersion: v1
kind: Secret
metadata:
    name: dumbbudget-secret
stringData:
    DUMBBUDGET_PIN: ENC[AES256_GCM,data:Ip/eUAs+,iv:BoJra76mY71KpUWZfIFzInWIdP/OKf+XYFVsnk6c/Jw=,tag:J12ZIxNX+LV3n2eeTu+/zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T20:52:14Z"
    mac: ENC[AES256_GCM,data:DzeWOyjP1XpL2qzEbMI66EQFSifVjBXHd/d1GlIjMAMgkUQR8b8P9fVNO0hGhYFuWwXxnCag+PlKRHzy+Wi7gcimnLZmr80/IpYVEXCAQIyBUlQy7i8os43iUwqrcFYoi2BKwz9knmGuykPBHObhLT5G7cEyKRMaEQBzjMGFZJk=,iv:S6Ise0PTGa0zgJlSGJeaxeBZoenHIh9Ajn7tUQ1mJYk=,tag:jLyqs9VF+uMsAc9AgZ8IFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
