---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.12.0
  interval: 10m0s
  values:
    controller:
      enableAnnotationValidations: false
      podAnnotations:
        linkerd.io/inject: enabled
      config:
        enable-brotli: true
        brotli-level: "6"
        use-gzip: true
      kind: DaemonSet
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 100%
        type: RollingUpdate
      allowSnippetAnnotations: true
      setAsDefaultIngress: true
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
      extraArgs:
        default-ssl-certificate: "cert-manager/${LETSENCRYPT_CERT}"
      service:
        loadBalancerIP: ${INGRESS_IP}
      resources:
        requests:
          cpu: 75m
          memory: 1Gi
        limits:
          memory: 1Gi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 75
        targetMemoryUtilizationPercentage: 75
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: prometheus
          additionalLabels:
            release: prometheus
