---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kube-vip-cloud-provider
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  interval: 10m0s
  values:
    config:
      image:
        repository: ghcr.io/kube-vip/kube-vip-cloud-provider
        tag: v0.0.9
      kubeVipCloudConfig: kubevip
