---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rclone
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: cronjob
        cronjob: &cronjob
          suspend: false
          concurrencyPolicy: Forbid
          schedule: "0 9 * * 1-6"
          successfulJobsHistory: 1
          failedJobsHistory: 1
          backoffLimit: 3
        containers: &containers
          main: # Dummy container
            image: &image
              repository: docker.io/rclone/rclone
              tag: 1.71.0
            args:
            - version
        initContainers: &initContainers
          # Order container execution with initContainer hack
          1-sync: &sync
            image: *image
            env:
              RCLONE_SRC: ceph:backup
              RCLONE_DST: "secret:"
            args:
            - sync
            - --log-level=INFO
            - --fast-list
            - --update
            - --use-server-modtime
            - $(RCLONE_SRC)
            - $(RCLONE_DST)
          2-cleanup:
            image: *image
            env:
              RCLONE_DST: b2:wuhoobackup
            args:
            - backend
            - cleanup-hidden
            - --log-level=INFO
            - $(RCLONE_DST)
      full:
        type: cronjob
        cronjob:
          <<: *cronjob
          schedule: "0 9 * * 0"
        containers: *containers
        initContainers:
          <<: *initContainers
          1-sync:
            <<: *sync
            args:
            - sync
            - --log-level=INFO
            - --fast-list
            - $(RCLONE_SRC)
            - $(RCLONE_DST)
    persistence:
      config:
        enabled: true
        type: secret
        name: rclone-secret
        globalMounts:
        - path: /config/rclone
