---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: simplytranslate
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        annotations:
          keel.sh/policy: force
          keel.sh/trigger: poll
          keel.sh/match-tag: "true"
          keel.sh/pollSchedule: "@every 240m"
        containers:
          main:
            image:
              repository: docker.io/schklom/simplytranslate
              tag: latest
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 5000
    ingress:
      main:
        enabled: true
        className: anubis
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: st.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
          ingress-anubis.jaredallard.github.com/difficulty: "4"
        hosts:
        - host: st.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
        tls:
        - hosts:
          - st.${DOMAIN}
          secretName: simplytranslate-cert
