---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/vaultwarden/server
              tag: 1.33.2-alpine
            env:
              SIGNUPS_ALLOWED: "false"
              WEBSOCKET_ENABLED: "true"
              LOG_FILE: /config/vaultwarden.log
              SMTP_PORT: !!str 587
            envFrom:
            - secretRef:
                name: vaultwarden-secret
    service:
      main:
        controller: main
        ports:
          http:
            port: &http 80
          websocket:
            port: &websocket 3012
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: vaultwarden.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: vaultwarden.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *http
          - path: /notifications/hub/negotiate
            pathType: Prefix
            service:
              identifier: main
              port: *http
          - path: /notifications/hub
            pathType: Prefix
            service:
              identifier: main
              port: *websocket
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
