apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    DOMAIN: ENC[AES256_GCM,data:QCeLSiR3GQdyTMB/y7L1ITKsteDAULnrMPw0eMs=,iv:iQUbxtW2F68TDO6G0cQ6WPKHfdljT20SvwAxDW8TiFE=,tag:yPP7YSHBNS6LR7Xne57tfg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ObwNRywzeq0Nqvr9BdqxSmPE8RMIBiCPKanTg8C56hLwlDMYA/My2vboHrVaiN6CaKvrKetLX8rFLXtH3XvrBgkxRJt+ulxG7EctjtlFgShs9x1I/T0/cvr/QhpnXCGLaL0zCEEo,iv:tbgpbk5T52v7ulYSvE1Ig5Uwzblfx+En87LSZoyX2js=,tag:d2Lpknk/3i5lrrpobRWB6Q==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:KNIr+6Vpl3dvjt82WHNzXw==,iv:ktrk0hJ8CkqrQlYmhNy+DoxEElJksXePocSat+RFarE=,tag:Hk8R6z+6sc5t1oVp8UOCTg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:o2oMntdH7sbyLlHnUZGugnnvSxPCYcLs1dz3zjGs,iv:4O6upIhniz85DX2LKkCLzrL2sRzdwGMoQUqoLxomhPM=,tag:tcNiW/ajCe3D0c0N8M0GyA==,type:str]
    SMTP_SECURITY: ENC[AES256_GCM,data:aV92g1DEB0U=,iv:XT/VU+MHv/ld6gZHVvvkuH/Ul780hWTwZeIM2z4hMyA=,tag:4U6TwV+5S2Oy1DwEuGg2EQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:6KuN4r8aOgLjbcq47JK7OLI=,iv:sQj1yyEsB2FePo2HMSXvhffSLfFa0914UaGfMt+0/nA=,tag:/eba95sp0bqnpxIzhQPVjQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3wbVyBP4njtX+hTfAtiPwPfT0klqYHrC+xMCk6qB4YaG3WVaEyDy57jxuNNh3IMU,iv:6ttel0XRZrqobTWUfhqMR+SAGoOva3UcXHd+JHH+O5g=,tag:jBnO9uqWooH3BIexo3JAEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T04:57:33Z"
    mac: ENC[AES256_GCM,data:Jc4/K/rB9omjSwxDuDWBoL3VkpWzaGFV7huDpXugTNPGDbI5Bg95bucHkQhlJBFUbGcuZmnx5m2x7Nl0FWNr+GTNgYETwGX7FPWxzKW7rO4IUambsJou+Rn6+CPD31lC0T/bROzqYr947QxCyZTeoq6RJYx3RcSiUa4yL5kZOGM=,iv:i8I0wwij4Tz5188SdUy2Wxjnb1JrGXv19wZWmGdARmM=,tag:B6wLZGpYf45YZXy7EhWSHg==,type:str]
    version: 3.13.3
