apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
stringData:
    config: ENC[AES256_GCM,data:L2VFQjECI/bj59GwG5lZ0KrxlM/65M8BjtN/AUWsqpKi+6BHhK8GqPOIfVzN630I13o+SQITRovXbfVUkFrIK47qJdGd22FOYB416Xm6j3ELvNtxhwFlt0IT9rUoJthJnHZQC/D2fBIepZLRlcjLpBo734WYVcA7G/eyp/aV4W3gi5GrLWWULBGiysHoVfqqAgz9jxdpzwCMwBPbuzmpyjcyxCRBRlZjnvirFi8Py7+oMWhoTVGcMVAE3NpGP7IO+Q8Y08/F,iv:K5yvn08T8xHreTQy8KvRffC1Va8GGtjH84D0djY62WQ=,tag:M3WRLJFjGfKZ98XA2zYolg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T04:19:33Z"
    mac: ENC[AES256_GCM,data:uqFiXpsL+u3uVIpiYbkcKH6eA6Sq8t/3DNSUjKlTCzSDAfjmWXGz7CBy0nVehZ40Eji7Ya4rpZy0RSgWVwqyqG7/ELomiptjHer9kk0QEqaxIfXVPJxJCqgdxQo4T2JqvJKz6aOaYfMC+nWu8zo/6WhO56Unp/49Epat7Wd1kx4=,iv:mmQhEIJI8EVIDfiIOQpOrzWXjdDsQw/stEZXHPmcOkU=,tag:6dVrj6qYsTKnyD2rBwZypQ==,type:str]
    version: 3.13.3
