apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
stringData:
    config: ENC[AES256_GCM,data:KusaieNQNL7mWyj6HORx9NN+6ixfcEzc3vNSbG81HZjXyydkr79sEpKtYkKYwUl5b9QGPBU+rz12Cyt60Ti+qz3OAmUNC+ecCj73ZWbvsXY+0h1+F5bR6Mf6gbqBTzEYEsi+TnptcCozRyXwAPp3uMeQZARLRCe6ybnoCB6At/4F8Sy7ntOltAGHoIqqpa22HvCBJJMpUD7qO68fvNPvc3xaMftA+ToBDvwU4ZvHhSCUbbl79W1iqrCOkC6k06VXHZeFnWl35fNOnHZmm5/SHdeKnKAuW/UbA3rg1DiggSg=,iv:v5cFwEtxfX0g/7TnRbVWZRbu+Q/t3K0nBVtulVpmVrE=,tag:0ozlC1voFbLeglnWx+mIOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T01:44:39Z"
    mac: ENC[AES256_GCM,data:r42m0swr3oksoynqZ1ce3eZU5MN8RevKONQs3swnj8iz2YzJzffqQ1Rc/96lpNxJXv3UFAKjGodFmfwr5UCZPT5FKa/wZ0WL4uO5H+LJ4uDPFflWHLK/CUPRgnQedJMDz8H3VOc6guWi3cFh/lANh4nkBSUVTUYZq4oZxhi1D+g=,iv:7RODh5pzR+5Dec8pQpmBy+c5e7AY81dVrCPK2+a55to=,tag:dw+PItbCeRd1A3S17Ugbsg==,type:str]
    version: 3.13.3
