apiVersion: v1
kind: Secret
metadata:
    name: hcloud-secret
    namespace: gitlab
stringData:
    HCLOUD_TOKEN: ENC[AES256_GCM,data:fjxzivwQYoZP0oho9b9gagBgzS84zDiFl4ADsiChcT5v3Vlud17Rfu1IQ/cbzlRdeq+QBrz0kVALV8iVM+/Yfw==,iv:VwYBvjoz+cYuu4z8knRqsCNTaBA6B6IuZVkN+oYFuyM=,tag:Za9VWZpr9fdv7K2GJq070w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T18:18:33Z"
    mac: ENC[AES256_GCM,data:uYFaIcK+M1hz26Fl74qdrZ0AoSIGPLjMetKTa8tDXWEPG1Jisj+HRn/QA0a4wEJas/iD0QTCg1MgT7OIEywddwVv0KPq5YiGI+5Jic+O1d+ytZdesVSta9OJ0vEo40QsEs78cv8p/U3X4fWXXYW1gJtbnjApUzywtlqmf6rj/DU=,iv:anJUYQpcMgze+8yhWFLDBWe+zM+02w5bZ1ctA0mOJeM=,tag:0nF79TPsyHdgzZy62ISUdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
