---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
- namespace.yaml
- zalando-secret.sops.yaml
- zalando-registry-secret.sops.yaml
- secret.sops.yaml
- gitlab-object-storage.sops.yaml
- gitlab-registry-storage.sops.yaml
- runner-cache-secret.sops.yaml
- valkey-secret.sops.yaml
- postgres.yaml
- valkey.yaml
- helmrelease.yaml
- ingress.yaml
- runner-arm64.yaml
- runner-amd64.yaml
- hcloud-secret.sops.yaml
- hcloud-cronjob.yaml
- renovate-secret.sops.yaml
- renovate.yaml
- volsync-gitaly
- vmpodscrape.yaml
- valkey-vmpodscrape.yaml
- networkpolicy.yaml
components:
- ../../../components/netpol/base
- ../../../components/netpol/postgres
- ../../../components/netpol/postgres-backup
- ../../../components/netpol/volsync
