---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: gitlab-postgres-cluster
  annotations:
    k8up.io/backup: "false"
spec:
  teamId: "gitlab"
  volume:
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: "1"
      memory: 1Gi
  numberOfInstances: 3
  users:
    # database owner
    gitlab:
    - superuser
    - createdb
    registry: []
  databases:
    gitlabhq_production: gitlab
    registry: registry
  postgresql:
    version: "16"
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
