apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: gitlab
stringData:
    DOCKER_DOCKER_IO_PASSWORD: ENC[AES256_GCM,data:OhF72/OB09U8Ward++skr+0S3xZ0sOilEk/6XgyZdEWSvUDj,iv:IvkK+Xys5MSkU0iaqK+pmaAzMAC+di6B174XLcUjwtk=,tag:kxrshtJh5XIVATjzhm0uSw==,type:str]
    DOCKER_DOCKER_IO_USERNAME: ENC[AES256_GCM,data:CYqqxuRVGW0=,iv:G+bcWArpKz9cbBa5VAYMV7VrvhYQu84l+GZGCBuBomE=,tag:OU3+Y5oc5W2HkqJBHqx/Wg==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:sPQTQP6ob6jEeRiwvaiT1XXmcCARKuP/HVeFqzaVUs/8BE2i3bZMhQ==,iv:lwX7ID+UKAoFV24xxnjPWjYFO518S1jQ7YjvtNeM4uA=,tag:oheWRc632oBn78NFGh9riw==,type:str]
    RENOVATE_AUTODISCOVER_FILTER: ENC[AES256_GCM,data:RaAZFVxmSmcCqOFlLm/t50FDpgEE0Ck=,iv:yxbhro+qkkhU9T0/ACkaYjgMbFIt8eISwzbtcMe4NbE=,tag:3XHzNq8vQ72ojrJlcS4uuw==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:a/uyLO810tXy/24bGotgIQIW3pEm3RlI5VcSz46uHLo=,iv:/CPV9Uc8MIIC3DnRwq4fZm4yCor9QIy8WIbGE8vfhJE=,tag:tpF19IL1K62mX9WocTZHGQ==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:YUFO2xpmpOryekCPy+lYZ0m5prU=,iv:22yumBRliAATLLSvHQ9AllAPAe61XZQayVxSg151wAU=,tag:e4c5nTfiygf/whUnPr0PGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T16:56:53Z"
    mac: ENC[AES256_GCM,data:686rN5EIyRpQq5mEpirO9DdfHAfZkgXZB8oNzlKe0uanuUifj7n9+z7E7t9A9hAwAn96McfEi8fypFsjIZ6scHnmvQ7Iz9dw9L400qQ2uWkCPtEI7Fm5CkmaAKlXb4b0h6Dgav5fwmURBFzlTVDLm25IeufX80Y/Nv6/8d/P3eM=,iv:kYLBlEn3NZrfV/X+udXPxFd3QxDokbnrhtE1321wAcQ=,tag:cz6i/OYj+2YgKUEGrGS2Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
