apiVersion: v1
kind: Secret
metadata:
    name: valkey-secret
    namespace: gitlab
stringData:
    default: ENC[AES256_GCM,data:76SiCyRzOJxjslYVSMQ5uwdLwJctiQ87kCtTmRL7J+wzgrfvVa78bFSnvf68Glvh,iv:jB7Lz5Nsr1UrQrr2bKFUCRA1VPfglRouDGgvevYHz7U=,tag:e1pAvF8YnFroy8TUJRnZng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T23:23:36Z"
    mac: ENC[AES256_GCM,data:F0Budh5Tv0PRnBmHzXfP5+KHKvGN58h6meuYDuLtVUVjEph6VxGY+jEmOQliGq5741XI/oAKNTZbmSoZM1f4he3bvMFWsxVnKBfvdVORib9v2wH8guRorS1l9kjZrk0gGUFA4zzTDc549y6kfCwaAA2dqEQCL3zT0YJ+iNQRSmI=,iv:X/x+X0/Ael+wXdV8IrDaRJpJ6hTWdqVpzy65hQSXheQ=,tag:cTh/MkzTnfy2FhpmmZVXlQ==,type:str]
    version: 3.13.3
