---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ytars-app-template
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        sysctls:
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
        - name: net.ipv6.conf.default.disable_ipv6
          value: "1"
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.wuhoo.xyz/jerry/ytars
              tag: v0.7.1-yt-dlp
            env:
              POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: ytars.ytars-postgres-cluster.credentials.postgresql.acid.zalan.do
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ytars.ytars-postgres-cluster.credentials.postgresql.acid.zalan.do
                    key: password
              POSTGRES_HOST: ytars-postgres-cluster
              POSTGRES_DB: ytars
              VIDEO_PATH: /videos
              SCAN_INTERVAL: 14400
              YT_DLP_DOWNLOAD_PATH: /videos
              YT_DLP_LIST_PATH: /videos/list.yaml
            securityContext:
              seLinuxOptions:
                user: system_u
                role: system_r
                type: container_t
                level: s0:c102,c902
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    persistence:
      videos:
        type: persistentVolumeClaim
        existingClaim: ytars-youtube-pvc
