apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:y2YNZxC0Hi2q,iv:tew9wSW+p/+XqPMcYpIoLxKpyre3F9IDsaHsJCtzbsg=,tag:gS+Y9/XuoUsqZCXNxjNBEQ==,type:str]
    LETSENCRYPT_URL: ENC[AES256_GCM,data:r7cbcnYL8HT/oER31YaukEHX1vPJXPuk0qzepQkk90pRSkv9s+1CKfhdGplNBw==,iv:1lreIocP6liE16CixVx1qEnBxc3Db1gpGrvKm8bmWGc=,tag://rZ/9Ac0bheE6qlD+exsQ==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:DJgBMeHp6Nd5EWDm//HnYMfhlDyrl6tobYdH5iGLuGfQCrwv0g==,iv:1pmbyt3p6I79cp5SLoYtLN0MebmKtfen+NncXDGo5s8=,tag:/HBZhp86t+/+hkjws6PSLQ==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BjgSa6tJxTSMuIe/kS6F9mKl4GY=,iv:LpCRdFF4D3zEaStWF3GtS4Q1NVrc9CveOxG5XHRwK/4=,tag:ceLtey3g6QhUO+3mJ9RydA==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:cN6VKR9/2KgJpEaBUipcRhURpzA=,iv:3MW9qNQ9amcvM0jwluSSOwj866easjZ7CXtFpTgJ3tc=,tag:Or2LHV0Y1q5w3gM1hw7GfQ==,type:str]
    LETSENCRYPT_CERT: ENC[AES256_GCM,data:9nkutMiG9ne0LcI=,iv:nzu+4CRzo72Q0DJj/zB6TOvVirZ9od0KdmbWD0pnbO4=,tag:8GmvImIlOXf+4/CvT5qPmw==,type:str]
    KUBE_API_CIDR: ENC[AES256_GCM,data:6TQOld7p3t4CfjptkXPbIYw=,iv:58i8y40V37fV06XFPYvsPYfGtr96SnRnNrMBow/Nez4=,tag:l2O+22F9FwrO5a/yoO9Jbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eCtZV0FiR1VQMEcwSFBu
            T0krUldLZHVCeWt5UlpZUGFXVEw0SFhFdkc4CmZPdGhiY3Via2RkVEI3RTRTRHh6
            cWhDQVRrQWxDOTdvNGlydGdPUHZVdDQKLS0tIFN2dmFYdlpQM01wRWY2Tm1zNm84
            STBlRUxoTFRvbWJWK21rZEo2aEpiQTQKkITQU3R6MPsdDGZ5ng4/ZRbkBHfFDM5E
            6M/nTT1ToNDab3KSf8d/YrQCb8E8+dXypRZq1o5QHz7fmxFF5oFhiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T03:38:42Z"
    mac: ENC[AES256_GCM,data:Ba2BKiF41cRackAakTDp5QH3Tl/tmNpoS3/xABdq5Bg0z3XfFqSZKV5X7Z7WydlsTzU0LbfVY4ussu/DGqEt4Xt86/8aEJOa6jNMxZ5TUWXc5WKNSk3P4ozS03PVHav7b5BLnNqdsat/IkB277A8MLXlx0i93n7ex3FDz1QwDHs=,iv:q6Wma92rBW7Nt7j1/ti+BvxZt2gxtgQxBLo+ZKTbHa8=,tag:PHmlvdDvGkhBoI+XrRovJA==,type:str]
    version: 3.7.3
