---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: archlinux
resources:
- cronjob.yaml
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configMapGenerator:
- name: mirror-sync
  files:
  - syncrepo.sh
