---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: synapse
  namespace: synapse
spec:
  values:
    signingkey:
      job:
        enabled: false
      existingSecret: synapse-extra-config
      existingSecretKey: signing.key
    serverName: ${DOMAIN}
    publicServerName: matrix.${DOMAIN}
    config:
      turnUris: ["turn:turn.${DOMAIN}?transport=udp", "turn:turn.${DOMAIN}?transport=tcp"]
    extraConfig:
      max_upload_size: 100M
      url_preview_enabled: true
      url_preview_ip_range_blacklist:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '100.64.0.0/10'
      - '169.254.0.0/16'
      - '::1/128'
      - 'fe80::/64'
      - 'fc00::/7'
      max_spider_size: 10M
      app_service_config_files:
      - /synapse/appservice/discord-registration.yaml
      - /synapse/appservice/signal-registration.yaml
      - /synapse/appservice/mautrix-discord-registration.yaml
      password_config:
        enabled: false
      sso:
        client_whitelist:
        - https://element.${DOMAIN}/
        - https://schildichat.${DOMAIN}/
        - https://cinny.${DOMAIN}/
        - https://hydrogen.${DOMAIN}/
        - https://app.element.io/
      stream_writers:
        events: event_persister1
        typing: typing_persister
        to_device: to_device_persister
        account_data: account_data_persister
        receipts: receipts_persister
        presence: presence_persister
    extraSecrets:
      redis:
        enabled: true
        host: synapse-keydb-headless
        port: 6379
    synapse:
      strategy:
        type: RollingUpdate
      extraVolumes: &volumes
      - name: extra-config
        secret:
          secretName: synapse-extra-config
          optional: false
      - name: appservice-config
        emptyDir: {}
      - name: discord-config
        secret:
          secretName: discord-config
          optional: false
      - name: signal-config
        secret:
          secretName: signal-config
          optional: false
      - name: mautrix-discord-config
        secret:
          secretName: mautrix-discord-config
          optional: false
      extraVolumeMounts: &volumeMounts
      - name: extra-config
        mountPath: /synapse/config/conf.d/oidc.yaml
        subPath: oidc.yaml
      - name: appservice-config
        mountPath: /synapse/appservice
      - name: discord-config
        mountPath: /synapse/appservice/discord-registration.yaml
        subPath: discord-registration.yaml
      - name: signal-config
        mountPath: /synapse/appservice/signal-registration.yaml
        subPath: registration.yaml
      - name: mautrix-discord-config
        mountPath: /synapse/appservice/mautrix-discord-registration.yaml
        subPath: registration.yaml
    workers:
      default:
        volumes: *volumes
        volumeMounts: *volumeMounts
      generic_worker:
        enabled: true
        replicaCount: 3
        listeners: [client, federation]
        csPaths:
        - "/_matrix/client/(api/v1|r0|v3|unstable)/publicRooms"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/joined_members"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/context/.*"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/members"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state"
        - "/_matrix/client/unstable/org.matrix.msc2946/rooms/.*/spaces"
        - "/_matrix/client/unstable/org.matrix.msc2946/rooms/.*/hierarchy"
        - "/_matrix/client/unstable/im.nheko.summary/rooms/.*/summary"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/account/3pid"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/keys/query"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/keys/changes"
        - "/_matrix/client/versions"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/joined_groups"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/publicised_groups"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/login"
        - "/_matrix/client/(r0|v3|unstable)/register"
        - "/_matrix/client/(r0|v3|unstable)/auth/.*/fallback/web"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/send"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/join/"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/profile/"
        paths:
        - "/_matrix/federation/v1/event/"
        - "/_matrix/federation/v1/state/"
        - "/_matrix/federation/v1/state_ids/"
        - "/_matrix/federation/v1/backfill/"
        - "/_matrix/federation/v1/get_missing_events/"
        - "/_matrix/federation/v1/publicRooms"
        - "/_matrix/federation/v1/query/"
        - "/_matrix/federation/v1/make_join/"
        - "/_matrix/federation/v1/make_leave/"
        - "/_matrix/federation/v1/send_join/"
        - "/_matrix/federation/v2/send_join/"
        - "/_matrix/federation/v1/send_leave/"
        - "/_matrix/federation/v2/send_leave/"
        - "/_matrix/federation/v1/invite/"
        - "/_matrix/federation/v2/invite/"
        - "/_matrix/federation/v1/query_auth/"
        - "/_matrix/federation/v1/event_auth/"
        - "/_matrix/federation/v1/exchange_third_party_invite/"
        - "/_matrix/federation/v1/user/devices/"
        - "/_matrix/federation/v1/get_groups_publicised"
        - "/_matrix/key/v2/query"
      event_persister1:
        enabled: true
        generic: true
        name: event_persister1
        listeners: [replication]
      typing_persister:
        enabled: true
        generic: true
        name: typing_persister
        listeners: [client, replication]
        csPaths:
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/typing"
      to_device_persister:
        enabled: true
        generic: true
        name: to_device_persister
        listeners: [client, replication]
        csPaths:
        - "/_matrix/client/(r0|v3|unstable)/sendToDevice/"
      account_data_persister:
        enabled: true
        generic: true
        name: account_data_persister
        listeners: [client, replication]
        csPaths:
        - "/_matrix/client/(r0|v3|unstable)/.*/tags"
        - "/_matrix/client/(r0|v3|unstable)/.*/account_data"
      receipts_persister:
        enabled: true
        generic: true
        name: receipts_persister
        listeners: [client, replication]
        csPaths:
        - "/_matrix/client/(r0|v3|unstable)/rooms/.*/receipt"
        - "/_matrix/client/(r0|v3|unstable)/rooms/.*/read_markers"
      presence_persister:
        enabled: true
        generic: true
        name: presence_persister
        listeners: [client, replication]
        csPaths:
        - "/_matrix/client/(api/v1|r0|v3|unstable)/presence/"
      federation_reader:
        enabled: true
        generic: true
        listeners: [federation]
        paths:
        - "/_matrix/federation/v1/send/"
      synchrotron:
        enabled: true
        generic: true
        listeners: [client]
        csPaths:
        - "/_matrix/client/(v2_alpha|r0|v3)/sync"
        - "/_matrix/client/(api/v1|v2_alpha|r0|v3)/events"
        - "/_matrix/client/(api/v1|r0|v3)/initialSync"
        - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync"
      sso:
        enabled: true
        generic: true
        listeners: [client]
        csPaths:
        - /_matrix/client/(api/v1|r0|v3|unstable)/login/sso/redirect
        - /_synapse/client/pick_idp
        - /_synapse/client/pick_username
        - /_synapse/client/new_user_consent
        - /_synapse/client/sso_register
        - /_synapse/client/oidc/callback
      pusher:
        enabled: true
      appservice:
        enabled: true
      federation_sender:
        enabled: true
      media_repository:
        enabled: true
      frontend_proxy:
        enabled: true
    redis:
      enabled: false
    externalRedis:
      host: synapse-keydb-headless
      existingSecret: synapse-redis
      existingSecretPasswordKey: redis-password
    persistence:
      enabled: true
      storageClass: ceph-cephfs-ssd-sc
      size: 60Gi
      accessMode: ReadWriteMany
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: matrix.${DOMAIN}
        external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        homelab/public: "true"