---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/syncthing/syncthing
              tag: 1.29.5
    service:
      main:
        controller: main
        ports:
          http:
            port: 8384
      listen:
        controller: main
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000
      discovery:
        controller: main
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        globalMounts:
        - path: /var/syncthing
