---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blink
resources:
- namespace.yaml
- zalando-secret.sops.yaml
- secret.sops.yaml
- keydb
- postgres.yaml
- helmrelease.yaml
- networkpolicy.yaml
components:
- ../../../components/netpol/base
- ../../../components/netpol/postgres
- ../../../components/netpol/postgres-backup
