---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-anubis
resources:
- ../../base/ingress-anubis
configMapGenerator:
- name: anubis-policy
  files:
  - botPolicies.yaml
  - cloud-alibaba.yaml
  - cloud-aws-ec2.yaml
  - cloud-byteplus.yaml
  - cloud-digitalocean.yaml
  - cloud-tencent.yaml
  options:
    # referenced by name inside the VOLUMES string below
    disableNameSuffixHash: true
patches:
- target:
    kind: HelmRelease
    name: ingress-anubis
  patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: ingress-anubis
    spec:
      values:
        config:
          WRAPPED_INGRESS_CLASS_NAME: nginx-public
          ENVIRONMENT_VARIABLES: POLICY_FNAME:/etc/anubis/botPolicies.yaml
          VOLUMES: '[{"name":"anubis-policy","configMap":{"name":"anubis-policy"}}]'
          VOLUME_MOUNTS: '[{"name":"anubis-policy","mountPath":"/etc/anubis","readOnly":true}]'
