---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefoxsync
  namespace: firefoxsync
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: docker.io/mozilla/syncserver
              tag: latest
            env:
              SYNCSERVER_PUBLIC_URL: https://firefoxsync.${DOMAIN}
              SYNCSERVER_BATCH_UPLOAD_ENABLED: "true"
              SYNCSERVER_FORCE_WSGI_ENVIRON: "true"
              PORT: "5000"
            envFrom:
            - secretRef:
                name: firefoxsync-secret
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 5000
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: firefoxsync.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
          nginx.ingress.kubernetes.io/proxy-body-size: 1G
        hosts:
        - host: firefoxsync.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
