---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shortpaste
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: shortpaste
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx-public
    ports:
    - port: 8080
      protocol: TCP
