---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: backup
spec:
  # The PVC to be backed up
  sourcePVC: data
  trigger:
    # Take a backup every 30 minutes
    schedule: "*/30 * * * *"
  restic:
    # Prune the repository (repack to free space) every week
    pruneIntervalDays: 7
    # Name of the Secret with the connection information
    repository: volsync-restic-config
    # Retention policy for backups
    retain:
      hourly: 6
      daily: 5
      weekly: 2
    # Clone the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Clone
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name
