---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 10m
  chart:
    spec:
      chart: linkerd-viz
      version: 30.12.11
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  dependsOn:
  - name: linkerd-control-plane
    namespace: linkerd
  install:
    crds: Create
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 20m
    recreate: true
    cleanupOnFail: true
  values: 
    enablePodAntiAffinity: true
    resources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
    tap:
      replicas: 3
      resources:
        cpu:
          limit: ""
          request: 25m
        memory:
          limit: 250Mi
          request: 50Mi
    dashboard:
      enforcedHostRegexp: '^(linkerd-viz\.${DOMAIN}|localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$'
      resources:
        cpu:
          limit: ""
          request: 25m
        memory:
          limit: 250Mi
          request: 50Mi
    grafana:
      resources:
        cpu:
          limit: ""
          request: 25m
        memory:
          limit: 1024Mi
          request: 50Mi
    prometheus:
      resources:
        cpu:
          limit: ""
          request: 100m
        memory:
          limit: 4096Mi
          request: 300Mi
