apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    namespace: monitoring
stringData:
    token: ENC[AES256_GCM,data:IWazwIYIFGwAW5C2ckdVdrZ7pAWuy60iSjr72Iku8rY=,iv:69i/kHLN42ke1rlYvvG0lI1AGPNClIbAiVRGQIR9Tnk=,tag:sLf7uiqkOIJNJMJcljot+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOWlCVEJXL0JCVTFtdTFU
            ZWJBU3g5RTZBNjhmcEpKZWdGclJ3NGtHZmhzCjBaNW91bE4rcHU0YjFXSDdJTUtZ
            Q1ArYkhmdjJFSTUyQWJUSU12NHBLdFUKLS0tIHRhY0VNekE5Z1pyUkRROUJVclhy
            cndKQmp1cEJnTnlGR2tLcXp2RVdtYkUKkOV/gddlD4reRKkc5WlD3scqh6/VpmG2
            zKywGg5WPwyCG/VHQKYFwUhCktbRfq0BS8pXeBBWjVveW78GQaWRGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:29:49Z"
    mac: ENC[AES256_GCM,data:hcHqWcXl7CdvrFgumNmdhPkn9wmTlL6B7EFaN/QsmPWA3+dcajizmYGix4ASEEbQcXYP5rHrmjiQCQChM+fX+CdJJSJrto5Vl5wQ9ExDT7y8MYqI6+r74WelVS0bf2UfN8mRbsa7OEHgddDCcTCWl2/4km+qdLeKFaN5N6Cjxqc=,iv:yTilpBkPpAObNI9Dqzc5ct82TsAzSIVwAgrmCCcFQDc=,tag:LWjrmcsMNSCspF0fQ1Zo3g==,type:str]
    version: 3.13.3
