apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:qjdnM9o=,iv:s+9CD5ai7ses2sQ0JgZYODM2HVOwl1m+sno/AWq5jHk=,tag:jdlmSlbcUODYUV71h4w4sw==,type:str]
    admin-password: ENC[AES256_GCM,data:ZbC17znoNqSnCIOo6eOhaXh5VERkx2pP/SYRAVWlcmM=,iv:EA0tjrlubx4TwTIqhNmKJ1e5VPoGwaH8HhfuzPMuZiA=,tag:vrDFVuVprWfs0p/yPLPSuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3amJlOUk5L3JaTzBSQ1pW
            Tms3VU9DNHRpODB3Y2lvb25kYXlobXJlY0hVCmV5T0pTU2IwU0JQL3VXUisweU5n
            QjNVTThCbjhYYnJzVWNZd2pkdjVCTzgKLS0tIHFERDJORUlVL216VC83QUdzR1l6
            VUtYTldBOUMxSklTRGZ2MCtIeWtiVW8KStiYh5ITzogc98XZPnTV4IBnCHyj3Vr3
            gFoo31B478qbzLmDGP1BMaqakfRvJ2Bnf6Yxv7Is/bZP0M7VV8A+yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:29:49Z"
    mac: ENC[AES256_GCM,data:8gVefEKo+kG77gHR1YJhdZ5ZjJdElj9xB72dP+Nk2ifDC3VMPniS04dptgWkTFOpSJaHY0EIuFFhcm3d9EGzIigoX/Bu+NXB6ruURHeDGuOo/jbHxcK0BHmyaOjpcSy6nI6UDn2bAX/iwgUuuBrgM9VpqnCClqak9nPAVjRVlRw=,iv:myKS70gHehRAHn86ExAdpafigxRNyMg8DS3cf/MyJpw=,tag:24w/c6xTu/u7izg1h2XVJA==,type:str]
    version: 3.13.3
