---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- grafana-secret.sops.yaml
- alertmanager-secret.sops.yaml
- prometheus-operator-crds.yaml
- helmrelease.yaml
- dashboards
