---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 10m
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.9.4
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  dependsOn:
  - name: cert-manager-trust
    namespace: cert-manager
  - name: linkerd-crds
    namespace: linkerd
  install:
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 20m
    recreate: true
    cleanupOnFail: true
  values:
    installNamespace: true
    identity:
      externalCA: true
      issuer:
        scheme: kubernetes.io/tls
    enablePodAntiAffinity: true
    proxy:
      resources:
        cpu:
          request: 25m
        memory:
          limit: 250Mi
          request: 20Mi
    proxyInit:
      resources:
        cpu:
          request: 25m
    controllerReplicas: 3
    controllerResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
    destinationResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
    identityResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 10Mi
    heartbeatResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
    proxyInjectorResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
    webhookFailurePolicy: Fail
    spValidatorResources:
      cpu:
        limit: ""
        request: 25m
      memory:
        limit: 250Mi
        request: 50Mi
