---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      setAsDefaultIngress: false
      ingressClassResource:
        name: nginx-onion
        enabled: true
        default: false
        controllerValue: k8s.io/ingress-nginx-onion
      ingressClass: nginx-onion
      watchIngressWithoutClass: false
      extraArgs: null
      service:
        loadBalancerIP: 10.40.0.92
      config:
        ssl-redirect: "false"
      kind: Deployment
      replicaCount: 2
      autoscaling:
        enabled: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: controller
                  app.kubernetes.io/instance: ingress-nginx-onion
