---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wiki
  namespace: wiki
spec:
  chart:
    spec:
      chart: wiki
      sourceRef:
        kind: HelmRepository
        name: requarks
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: wiki-secret
    valuesKey: databaseURL
    targetPath: externalPostgresql.databaseURL
  values:
    image:
      repository: ghcr.io/requarks/wiki
      tag: 2.5.302
    ingress:
      enabled: true
      className: nginx-public
      annotations:
        homelab/public: "true"
        external-dns.alpha.kubernetes.io/hostname: wiki.${DOMAIN}
        external-dns.alpha.kubernetes.io/target: ${DOMAIN}
      hosts:
      - host: wiki.${DOMAIN}
        paths:
        - path: /
          pathType: Prefix
    externalPostgresql: 
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    postgresql:
      enabled: false
