---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7
            env:
              # admin
              PAPERLESS_ADMIN_MAIL: fake@example.com
              PAPERLESS_ADMIN_USER: admin
              # OIDC
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              # Database
              PAPERLESS_DBENGINE: postgresql
              PAPERLESS_DBHOST: "paperless-postgres-cluster"
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: &pgsecret paperless.paperless-postgres-cluster.credentials.postgresql.acid.zalan.do
                    key: username
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: *pgsecret
                    key: password
              # Paperless tika/gotenberg
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
              PAPERLESS_URL: https://paperless.${DOMAIN}
              # Misc
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_CONSUMER_POLLING: 60
              USERMAP_GID: 1000
              USERMAP_UID: 1000
            envFrom:
            - secretRef:
                name: paperless-secret
      gotenberg:
        containers:
          main:
            image:
              repository: docker.io/gotenberg/gotenberg
              tag: 8.17.3
            args:
            - gotenberg
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
      tika:
        containers:
          main:
            image:
              repository: docker.io/apache/tika
              tag: 3.1.0.0
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8000
      gotenberg:
        controller: gotenberg
        ports:
          http:
            port: 3000
      tika:
        controller: tika
        ports:
          http:
            port: 9998
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: paperless.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: paperless.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
      media:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
      consume:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
      export:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
