---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinny
  namespace: synapse
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v4.8.1
            resources:
              requests:
                cpu: 25m
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 80
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: cinny.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: cinny.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: configMap
        name: cinny-config
        globalMounts:
        - path: /app/config.json
          subPath: config.json
    configMaps:
      config:
        data:
          config.json: |-
            {
              "defaultHomeserver": 0,
              "homeserverList": [
                "${DOMAIN}",
                "matrix.org"
              ],
              "allowCustomHomeservers": true
            }
