---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
  namespace: synapse
spec:
  chart:
    spec:
      chart: matrix-synapse
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: synapse-redis
    valuesKey: redis-password
    targetPath: extraSecrets.redis.password
  values:
    image:
      repository: ghcr.io/element-hq/synapse
      tag: v1.125.0
    wellknown:
      enabled: true
      replicaCount: 2
      extraData:
        support:
          admins:
          - matrix_id: '@jerry:${DOMAIN}'
            role: 'admin'
      resources:
        limits:
          memory: 15Mi
        requests:
          cpu: 5m
          memory: 15Mi
    config:
      reportStats: false
      enableRegistration: false
    extraConfig:
      use_presence: true
      enable_search: true
    extraSecrets:
      redis:
        enabled: true
        host: synapse-redis-master
        port: 6379
    synapse:
      strategy:
        type: Recreate
      extraEnv: &extraEnv
      - name: LD_PRELOAD
        value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      - name: SYNAPSE_CACHE_FACTOR
        value: "1.0"
      podSecurityContext:
        seLinuxOptions:
          user: system_u
          role: system_r
          type: container_t
          level: "s0:c103,c903"
    workers:
      default:
        extraEnv: *extraEnv
    postgresql:
      enabled: false
    externalPostgresql:
      host: synapse-postgres-cluster-pooler
      port: 5432
      username: synapse
      existingSecret: synapse.synapse-postgres-cluster.credentials.postgresql.acid.zalan.do
      existingSecretPasswordKey: password
    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: synapse-redis
      architecture: replication
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
    ingress:
      enabled: true
      className: nginx-public
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 200M
