---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- zalando-secret.sops.yaml
- synapse-redis-secret.sops.yaml
- postgres.yaml
- helmrelease.yaml
- element-web.yaml
- cinny.yaml
- federation-tester.yaml
- volsync
- vmpodscrape.yaml
