---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: synapse-postgres-cluster
  namespace: synapse
  annotations:
    k8up.io/backup: "false"
spec:
  teamId: "synapse"
  volume:
    size: 20Gi
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: "1"
      memory: 1Gi
  numberOfInstances: 3
  users:
    # database owner
    synapse:
    - superuser
    - createdb
  databases:
    synapse: synapse
  postgresql:
    version: "15"
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
