gitlab_token: ENC[AES256_GCM,data:EtY3fIQbVwTzOJD7aVR7PCX2EjhBKd3HlFYLTcH+JQbyOdEsXeUE1IS55ZuW5+1xIeopi8A77cGMm1yAkhQ=,iv:npzkkG+u2c0/VUEBoTrVxcxuJrbCdJEVGKiEWvbOqG8=,tag:KZ1XK7paD1LFus4RQAVc9Q==,type:str]
hcloud_token: ENC[AES256_GCM,data:yr6EvfpFK3H0sZEt1M60zx/pBYVcma/B2ZI97WQ/xcpip+T9mGNN4/aelK4C3kTBFXgQuSRRg76XmEsLgTn4wA==,iv:A5USJ3oSDE9VdRPMX8ZUgfv4t7/Zbf2mun6NpKEOnGE=,tag:7PTXk7GYbF5QfMy0u4XIfQ==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:Rs5dxo/6yVslY07+CoItotm3cq6zrJK3ENGdxCZwaHokCfmMvTawjA==,iv:jhcQObFXftcLNCmfzx1/QgwtmFChY5d/u0ZW9+KhY7k=,tag:nOLMDnKKidj1md430Ug1CA==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:qAi3A0SpipnD++QY+8n9ttJXu9vNf1SXM4eMF74DYPo=,iv:fDA8e+CtUpxgxb9z2kj0cRwkJHhhLAYdXSoGeHAACnk=,tag:j+wrcQ8vlremfXMkFBWbqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOFFMcHBkRzFHcEJ3MjZa
            aWJVaU5TMEsydmtNVUFxbmNUODB6T2tkL200CkpOckRRdXhjV3RsSkFVSmNWMG8w
            bHRNK0FaUWR2aEFQTVlubi9sc0RJZ0EKLS0tIHY5T1dzZEp5cjVMYTMzWmo3N1Yw
            aVFQL2oxNFI0RWhBM3R2QURsK2hrOGcKz3pzyYZpSmmeY2ZS1YCqGKqDcFC2N5tw
            DKeM/OgSVplyJCCqU2U9S+Cd54HYroEkLZLdwEP5y1z/f17qBuZCgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    lastmodified: "2026-09-14T04:28:18Z"
    mac: ENC[AES256_GCM,data:TRe8R5iDAhnjcep98rWgSzbgkL0v+V4woVZc+4aVciDiciDgmhwEDpxXb/u89E1zkhjftbD0/Wgxx5pODGwaN8gMVEawXvQ0z34R8cxtZ9DbsioEF04/7za9a8Ut81El9QUNZxWTMtoCtmkpOkj7jYPjBF0gnj85/rP95VpCLxY=,iv:wp8LJkB5H4QmEgXslH8xZ4fCO+swKnCy3D0m2b2tIv8=,tag:GQRad7HtNELNYVKJ3veEMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
