---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2025.8.3
      env:
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME
        value: "false"
      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik.authentik-postgres-cluster.credentials.postgresql.acid.zalan.do
            key: username
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik.authentik-postgres-cluster.credentials.postgresql.acid.zalan.do
            key: password
      - name: AUTHENTIK_REDIS__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-keydb-secret
            key: password
      envFrom:
      - secretRef:
          name: authentik-secret
    authentik:
      email:
        host: smtp.sendgrid.net
        port: 587
        use_tls: true
        use_ssl: false
        from: "authentik@no-reply.${DOMAIN}"
      postgresql:
        host: authentik-postgres-cluster
        name: authentik
      redis:
        host: authentik-keydb-headless
      error_reporting:
        enabled: false
      disable_startup_analytics: true
    server:
      ingress:
        enabled: true
        ingressClassName: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: auth.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - auth.${DOMAIN}
        paths:
        - /
        pathType: Prefix
    postgresql:
      enabled: false
    redis:
      enabled: false
