---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
- namespace.yaml
- limitrange.yaml
- zalando-secret.sops.yaml
- secret.sops.yaml
- postgres.yaml
- helmrelease.yaml
- vmpodscrape.yaml
- networkpolicy.yaml
components:
- ../../../components/netpol/base
- ../../../components/netpol/postgres
- ../../../components/netpol/postgres-backup
