apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:hQ8GGvLFZkd/6oCSJNRVNYYWs6XuQUsvDAdgA7+JExKRHnwp3V6ZWac5wq9GOgbPhpM=,iv:D+Ga7KIMIanZi4b1LSXfwjkuptSitsfZD7QmMjHNdlU=,tag:ik7e9L434SqZkvgY/z5YGw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:bWFvTCZJW5IP8kU5W9sl2jfeiAbFyCgXAu2dTWXz5ZuQWkZI,iv:wn0wkMXhBAy0bCFz641CNnKVPmgB32NbfccYr5c7M7g=,tag:coZyOsBGo/4iJ1LdvyzyOg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:xrRY66BJXvlSnngTywRW,iv:70M7IfhiZ+LSP6RE0Ur8Axe23RGmOXwAHYUTnMQdNrI=,tag:V0X5K6ghO+ATL6wXkrWHYA==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:DpMmchl3sVXhjgP6fQXK5iHjUNhzYXZdn/cNPudO2gsDVnLUXX1nPJcBT09/+INM,iv:QA732IBay4L4sseO8D7WsRnR+sB0IY8xuBN08YaHjL8=,tag:qmfHG+Wj2WJ1nK9oSO1Zqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T04:49:34Z"
    mac: ENC[AES256_GCM,data:OI07ouKH1pwDVjQcMnpbCj7DJtihRXAinuGoR4Gc3neyD9QaJdpwjZvOJaAq7XJQlyUuKn7heGx3zT+YqGAileUtrxQeFUvShBBttFPudgaM9EyGrFs037jJKmeXGSuDdCYQCSGYEv0z/pQqUv5zACM5r5UGtk1xMvN9iim2OX4=,iv:aA8p0zr9fuUCEWfBe4+ACjLeCio3djtbig8DZ9WHWIw=,tag:IL2h6t+HG0IpJNJITMDi6g==,type:str]
    version: 3.13.3
