---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overleaf
  namespace: overleaf
spec:
  chart:
    spec:
      chart: overleaf
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: overleaf-secret
    valuesKey: OVERLEAF_MONGODB_URL
    targetPath: env.SHARELATEX_MONGO_URL
  - kind: Secret
    name: overleaf-secret
    valuesKey: OVERLEAF_MONGODB_PASSWORD
    targetPath: mongodb.auth.rootPassword
  - kind: Secret
    name: overleaf-secret
    valuesKey: OVERLEAF_REDIS_PASSWORD
    targetPath: env.SHARELATEX_REDIS_PASS
  - kind: Secret
    name: overleaf-secret
    valuesKey: OVERLEAF_REDIS_PASSWORD
    targetPath: redis.auth.password
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: overleaf.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: overleaf.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
    env:
      TZ: UTC
      SHARELATEX_SITE_URL: "https://overleaf.${DOMAIN}"
      SHARELATEX_APP_NAME: "Overleaf (${DOMAIN})"
      SHARELATEX_REDIS_HOST: overleaf-redis-master
      REDIS_HOST: overleaf-redis-master
      SHARELATEX_BEHIND_PROXY: true
      SHARELATEX_RESTRICT_INVITES_TO_EXISTING_ACCOUNTS: true
      SHARELATEX_ALLOW_PUBLIC_ACCESS: true
      SHARELATEX_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: true
    persistence:
      data:
        accessMode: ReadWriteOnce
        enabled: true
        retain: true
        size: 10Gi
        type: pvc
        mountPath: /var/lib/sharelatex
    mongodb:
      enabled: true
      architecture: standalone
      auth:
        enabled: true
      persistence:
        enabled: true
        accessModes:
        - ReadWriteOnce
    redis:
      enabled: true
      auth:
        enabled: true
