---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: libreddit
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        annotations:
          keel.sh/policy: force
          keel.sh/trigger: poll
          keel.sh/match-tag: "true"
          keel.sh/pollSchedule: "@every 240m"
        containers:
          main:
            image:
              repository: quay.io/redlib/redlib
              tag: latest
            env:
              REDLIB_DEFAULT_SHOW_NSFW: "on"
              REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION: "on"
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        advancedMounts:
          main:
            warp:
            - path: /var/lib/cloudflare-warp
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: redlib.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
        hosts:
        - host: redlib.${DOMAIN}
          paths: &paths
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
        tls:
        - hosts:
          - redlib.${DOMAIN}
          secretName: redlib-cert
      libreddit:
        enabled: true
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: libreddit.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
          nginx.ingress.kubernetes.io/permanent-redirect: "https://redlib.${DOMAIN}$request_uri"
        hosts:
        - host: libreddit.${DOMAIN}
          paths: *paths
        tls:
        - hosts:
          - libreddit.${DOMAIN}
          secretName: libreddit-cert
