---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: descheduler
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 10m0s
  values:
    schedule: "*/10 * * * *"
    deschedulerPolicy:
      profiles:
      - name: default
        pluginConfig:
        - name: DefaultEvictor
          args:
            podProtections:
              defaultDisabled:
              - PodsWithLocalStorage
              extraEnabled:
              - PodsWithPVC
        - name: RemoveDuplicates
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingNodeTaints
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: LowNodeUtilization
          args:
            thresholds:
              cpu: 40
              memory: 40
              pods: 30
            targetThresholds:
              cpu: 70
              memory: 70
              pods: 40
        plugins:
          balance:
            enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
            - LowNodeUtilization
          deschedule:
            enabled:
            - RemovePodsHavingTooManyRestarts
            - RemovePodsViolatingNodeTaints
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity

