---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptimers
  namespace: uptimers
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.wuhoo.xyz/jerry/uptimers
              tag: v0.3.0
            env:
              CONFIG_PATH: /config/config.yaml
              POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: uptimers.uptimers-postgres-cluster.credentials.postgresql.acid.zalan.do
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: uptimers.uptimers-postgres-cluster.credentials.postgresql.acid.zalan.do
                    key: password
              POSTGRES_HOST: uptimers-postgres-cluster
              POSTGRES_DB: uptimers
              RUST_LOG: info
            envFrom:
            - secretRef:
                name: uptimers-secret
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: uptimers.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: uptimers.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: configMap
        name: uptimers-config
    configMaps:
      config:
        data:
          config.yaml: |-
            sites:
              - site: https://auth.wuhoo.xyz/
                name: Authentik
              - site: https://matrix.wuhoo.xyz/_matrix/static/
                name: Matrix
              - site: https://element.wuhoo.xyz/
                name: Element
              - site: https://cinny.wuhoo.xyz/
                name: Cinny
              - site: https://fmd.wuhoo.xyz/
                name: FindMyDevice
              - site: https://gitlab.wuhoo.xyz/-/liveness
                name: GitLab
              - site: https://photos.wuhoo.xyz/
                name: Immich
              - site: https://jellyfin.wuhoo.xyz/
                name: Jellyfin
              - site: https://wuhoo.xyz/
                name: Landing Page
              - site: https://mollysocket.wuhoo.xyz/
                name: Mollysocket
              - site: https://cloud.wuhoo.xyz/status.php
                name: Nextcloud
              - site: https://ntfy.wuhoo.xyz/
                name: Ntfy
              - site: https://paperless.wuhoo.xyz/
                name: Paperless
              - site: https://paste.wuhoo.xyz/
                name: Privatebin
              - site: https://send.wuhoo.xyz/
                name: Send
              - site: https://tachidesk.wuhoo.xyz/
                name: Tachidesk
              - site: https://vaultwarden.wuhoo.xyz/
                name: Vaultwarden
