---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: appscode
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.appscode.com/stable
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.goauthentik.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://ceph.github.io/csi-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.gitlab.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://k8s-at-home.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/dashboard/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kube-vip.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loftsh
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.loft.sh
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://nextcloud.github.io/helm/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openfaas
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://openfaas.github.io/faas-netes/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: chrisingenhaag
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://chrisingenhaag.github.io/helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kasten
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.kasten.io/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keel
  namespace: flux-system
spec:
  interval: 10m0s
  url:  https://charts.keel.sh
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/descheduler/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ananace
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://ananace.gitlab.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: requarks
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.js.wiki
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: enapter
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://enapter.github.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: renovate
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://docs.renovatebot.com/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: privatebin
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://privatebin.github.io/helm-chart
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://releases.rancher.com/server-charts/stable
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://bjw-s-labs.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.linkerd.io/stable
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://portainer.github.io/k8s/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://immich-app.github.io/immich-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bugfest
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://bugfest.github.io/tor-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up-io
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://k8up-io.github.io/k8up
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://emberstack.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: invidious
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts-helm.invidious.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://backube.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: angelnu
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://angelnu.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anza-labs
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://anza-labs.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ingress-anubis
  namespace: flux-system
spec:
  interval: 10m0s
  url: oci://ghcr.io/jaredallard/helm-charts/ingress-anubis
  ref:
    tag: 1.7.3
