apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-oidc
stringData:
    OpenIDConfig__AuthURL: ENC[AES256_GCM,data:09ZfWU2Q2CjPrhxySJW6QVj0jhoZ2pYudTYTm4zb9UVPu7Kr033dXm8q0gGUsC4=,iv:yhD6SfUQEDr+A/TPXVeUwkKoJnG2CAt8siHMhekjZ+Q=,tag:M5ZNFSD7WZEjAwsofy6gBw==,type:str]
    OpenIDConfig__ClientId: ENC[AES256_GCM,data:+KEozn6LcwhAaCXXLAx1FE6ETH/b1NkHzpuJvl7oyd3AITuDwAJu5g==,iv:G18AGWIhz3g9I/tvywg4bM+RVrHczhFp/ctuGUYx9aw=,tag:TB1BF7O3HGORbjQ71M5ihg==,type:str]
    OpenIDConfig__ClientSecret: ENC[AES256_GCM,data:rGH7m7PJXvHf2iaElm4jnszycCqqzwkIybrj8iC8CCYTZcI8uFrW6pEhyR4+deyFlI7RICxzm3QBT22hjqhPbEvDGcAqrZd2VzPR7cMXh8bZKqm5vHobCHNPgYO++isB6QTYnrYE52LhzexHy8Pqpn+LxW8DGIBB0sF1wV+E1zw=,iv:ZEAwxLape47LppqEq/cDhB19hCt27FoUZxRVVTrqtHg=,tag:FUDPvxkaPH9TMSAOyAZNuQ==,type:str]
    OpenIDConfig__DisableRegularLogin: ENC[AES256_GCM,data:KbGoqoE=,iv:Dultut/HfHm5n5ncgR8dfpuvjxlGlY4dF44c/Lq8y1I=,tag:sRz+gJZHjltpiUKH2Rgchw==,type:str]
    OpenIDConfig__LogOutURL: ENC[AES256_GCM,data:y+K7p0MnYyWs6DtCyHQ4DkmF94gWkiQk8mlJJwno6IEcGALCB+6Ez0xeJD/VddSwfl0SBPbsA/pPR0hD,iv:zUZaa88IHa6ERaRw4jcg4VZ0BsdRYbIs+b0o3IFHMNw=,tag:DGZJ4xIOvk3rqqwDwu6f+A==,type:str]
    OpenIDConfig__Name: ENC[AES256_GCM,data:ppw2vxcm2qV6,iv:fs+tlHZxeJQWKcWXZYKA1gkbcolOpf8FmjbbH60E/cI=,tag:42LE7m2B55aQ2rKPPtTVSw==,type:str]
    OpenIDConfig__RedirectURL: ENC[AES256_GCM,data:LQARPG+yVUFqVWhVEoR6QqjrfE3+aZbCWgVOO7y/gXZ5ntSE38elE+zS7T5M,iv:rgEP40pxzLCPeamDhG0aH7T7Ehgc7J9tLCc6NYvDdeM=,tag:/wR6NXhLg/ttqckA/gIiEQ==,type:str]
    OpenIDConfig__Scope: ENC[AES256_GCM,data:R/MP6rj034LiiPol,iv:FjvNsHJfqI99sfB/PtuA2pTAFnq/YSgLegv1s18/7CE=,tag:xDd0lvCYkqJ6pv0PDc7Dfw==,type:str]
    OpenIDConfig__TokenURL: ENC[AES256_GCM,data:+Xa4M5FdJXa/kBnNSlBNaqacF87PTDRugNKGro1/H34xdsQqHKSDIUNtNQ==,iv:n1GdDs5Gr1Dlty6XR9axIA+UZ3daZf2eSeilUnVCN+Q=,tag:d78Tc8AQ+Brqsa46CPo5xw==,type:str]
    OpenIDConfig__UsePKCE: ENC[AES256_GCM,data:DQ/YwO4=,iv:IPBeJuar43Fb00td12IHi8hR+SGvflxVRsjl8VFvXuU=,tag:umpxfr+zR394s8gEmTUi1g==,type:str]
    OpenIDConfig__UserInfoURL: ""
    OpenIDConfig__ValidateState: ENC[AES256_GCM,data:KW93/5g=,iv:D1xESG93m4C4Qts1j35dMhgdHDv6jQrL3b1JVV9DQBo=,tag:6q5U8g2zLdoP2HE1MEvJ3g==,type:str]
sops:
    age:
        - recipient: age145q8qdg9ljfsl88dl3d5j9qqcq62nhev49eyqj30ssl5ryqc5vgssrmuau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUZNN09yaWREMUR1eWpv
            b3dJcEh3WEFlT3BVYWhyMzgxZ3FxMVlsaEFvCnJWb0Q0Sk1mamJjMnJ2a3pzVDZn
            OUJ3ZmsrQXMvbWNDUUhPNWMyTk5HTnMKLS0tIFpOZUV3YWlYUi9kVHp2bFFLcUJv
            dS9zT2dXakdxUXJxZHBCNXpVdE9FMFUKuAsrsm9rtF/GymfpIdSHfIFMOQ6vipi2
            Pb+iY1+tWdiq5lIZARCvav7mR/jaVGQDFmRLK2rvxUvHBf0tlgrDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-27T22:57:14Z"
    mac: ENC[AES256_GCM,data:JBuRF4sulNXkh5VA+NRnzgUDpfGVkOY9U9D3kx5l29n4QCY5fYQlIiBFG/GDd1dxjueqbqnezv8cF1XKZBpfHdFWzdS8o5l15jAovI1yf8fs061zcYxQmuSWlz4/oMSb28QRgXirF1M+uL9nYK62dWl2c9YmzbyFMpW1uTEgYmk=,iv:slGnCIxwdSj7KafJ9T2BfAoemKxsYOj03pKgMqXqAa8=,tag:Fh0hKILwphKgPR9kqW7nAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
