---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: ceph-csi-cephfs
spec:
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
  interval: 10m0s
  values:
    csiConfig:
    - clusterID: ${CEPH_CLUSTER_ID}
      monitors:
      - ${CEPH_MON_0}
      - ${CEPH_MON_1}
      - ${CEPH_MON_2}
    provisioner:
      snapshotter:
        image:
          repository: registry.k8s.io/sig-storage/csi-snapshotter
          tag: v8.1.0
