---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mollysocket
  namespace: mollysocket
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/mollyim/mollysocket
              tag: 1.6.0
            env:
              MOLLY_DB: /data/db.sqlite
              MOLLY_ALLOWED_ENDPOINTS: '["https://ntfy.${DOMAIN}"]'
              MOLLY_ALLOWED_UUIDS: '["6cb74e4d-41e2-44b9-a897-9a6fbdd8b4d4"]'
              MOLLY_HOST: 0.0.0.0
              RUST_LOG: info
            envFrom:
            - secretRef:
                name: mollysocket-secret
            args:
            - server
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8020
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: mollysocket.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: mollysocket.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
