---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.14.0
            env:
              TZ: UTC
              NTFY_BASE_URL: https://ntfy.${DOMAIN}
            args:
            - serve
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 80
    ingress:
      main:
        enabled: true
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: ntfy.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: ntfy.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
        globalMounts:
        - path: /var/cache/ntfy
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
        - path: /var/lib/ntfy
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
        - path: /etc/ntfy
