---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: send
  namespace: send
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.gitlab.com/timvisee/send
              tag: v3.4.23
            env:
              BASE_URL: "https://send.${DOMAIN}"
              FILE_DIR: /uploads
              MAX_EXPIRE_SECONDS: "604800"
              MAX_FILE_SIZE: "10737418240"
              REDIS_HOST: send-keydb-headless
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: send-keydb-secret
                    key: password
              TZ: UTC
        initContainers:
          redis-isready:
            image:
              repository: docker.io/bitnami/redis
              tag: 7.4.1-debian-12-r1
            command:
            - "/bin/sh"
            - "-c"
            - "until redis-cli -h send-keydb-headless ping ; do sleep 2 ; done"
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 1443
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: send.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
          nginx.ingress.kubernetes.io/proxy-body-size: 15G
          nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
        hosts:
        - host: send.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      uploads:
        type: persistentVolumeClaim
        storageClass: ceph-rbd-hdd-sc
        accessMode: ReadWriteOnce
        size: 250Gi
        retain: true
