---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pixivfe
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: docker.io/vnpower/pixivfe
              tag: v2.11@sha256:6e2ed3ecbad0190c0aade99eb8ecb647dd8dcb0f850749095b2c1fca3c0ad0a2
            env:
              PIXIVFE_HOST: 0.0.0.0
              PIXIVFE_IMAGEPROXY: https://pximg.${DOMAIN}
            envFrom:
            - secretRef:
                name: pixivfe-secret
      pximg:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/nginxinc/nginx-unprivileged
              tag: 1.27.3-alpine3.20
    persistence:
      nginx-cache:
        type: emptyDir
        sizeLimit: 5Gi
        advancedMounts:
          pximg:
            main:
            - path: /cache
      nginx-config:
        type: configMap
        name: pixivfe-pximg-config
        advancedMounts:
          pximg:
            main:
            - path: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8282
      pximg:
        controller: pximg
        ports:
          http:
            port: &pximg-port 8080
    ingress:
      main:
        enabled: true
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: pixiv.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
        hosts:
        - host: pixiv.${DOMAIN}
          paths: &paths
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
        tls:
        - hosts:
          - pixiv.${DOMAIN}
          secretName: pixiv-cert
      pximg:
        enabled: true
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: pximg.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
        hosts:
        - host: pximg.${DOMAIN}
          paths: &paths
          - path: /
            pathType: Prefix
            service:
              identifier: pximg
              port: *pximg-port
        tls:
        - hosts:
          - pximg.${DOMAIN}
          secretName: pximg-cert
    configMaps:
      pximg-config:
        data:
          default.conf: |-
            proxy_cache_path /cache levels=1:2 keys_zone=pximg:10m max_size=5g inactive=7d use_temp_path=off;

            server {
              listen 8080;

              access_log off;

              location / {
                proxy_cache pximg;
                proxy_pass https://i.pximg.net;
                proxy_cache_revalidate on;
                proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
                proxy_cache_lock on;
                add_header X-Cache-Status $upstream_cache_status;
                proxy_set_header Host i.pximg.net;
                proxy_set_header Referer "https://www.pixiv.net/";

                proxy_cache_valid 200 7d;
                proxy_cache_valid 404 5m;
              }
            }