---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallabag
  namespace: wallabag
spec:
  chart:
    spec:
      chart: wallabag
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: wallabag.wallabag-postgres-cluster.credentials.postgresql.acid.zalan.do
    valuesKey: password
    targetPath: env.POSTGRES_PASSWORD
  - kind: Secret
    name: wallabag.wallabag-postgres-cluster.credentials.postgresql.acid.zalan.do
    valuesKey: password
    targetPath: env.SYMFONY__ENV__DATABASE_PASSWORD
  - kind: Secret
    name: wallabag-keydb-secret
    valuesKey: password
    targetPath: env.SYMFONY__ENV__REDIS_PASSWORD
  values:
    image:
      repository: docker.io/wallabag/wallabag
      tag: 2.6.12
    env:
      TZ: UTC
      POSTGRES_USER: wallabag
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: wallabag-postgres-cluster
      SYMFONY__ENV__DATABASE_PORT: "5432"
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__REDIS_HOST: wallabag-keydb-headless
      SYMFONY__ENV__REDIS_PORT: 6379
      SYMFONY__ENV__DOMAIN_NAME: http://wallabag.${DOMAIN}
      SYMFONY__ENV__SERVER_NAME: "${DOMAIN} Wallabag"
      SYMFONY__ENV__FOSUSER_REGISTRATION: false
      POPULATE_DATABASE: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-public
        annotations:
          homelab/public: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: 25M
          external-dns.alpha.kubernetes.io/hostname: wallabag.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: wallabag.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
    persistence:
      images:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
        type: pvc
        mountPath: /var/www/wallabag/web/assets/images
    redis:
      enabled: false
