---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: feishin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 3
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/jeffvli/feishin
              tag: 0.7.1
            env:
              SERVER_NAME: Jerryfin
              SERVER_TYPE: jellyfin
              SERVER_URL: https://jellyfin.${DOMAIN}
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 64Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 9180
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: feishin.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: feishin.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
