---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.5.1
            env:
              TZ: UTC
              LOG_LEVEL: info
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 5055
    ingress:
      main:
        enabled: true
        className: nginx-public
        hosts:
        - host: jellyseerr.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        globalMounts:
        - path: /app/config
