---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes-excludes: media
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.11.1
            env:
              TZ: UTC
            securityContext:
              seLinuxOptions:
                user: system_u
                role: system_r
                type: container_t
                level: s0:c123,c456
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8096
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: jellyfin.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: jellyfin.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        retain: true
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        retain: true
      media:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
      transcode:
        type: emptyDir
        sizeLimit: 50Gi
        globalMounts:
        - path: /config/transcodes
