---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes-excludes: media
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.8.3.8933
            env:
              TZ: UTC
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                      read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                  failureThreshold: 5
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 7878
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
      media:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
