---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tachidesk
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes-excludes: tachidesk
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.1910
            env:
              DOWNLOAD_AS_CBZ: "true"
              BASIC_AUTH_ENABLED: "true"
              WEB_UI_CHANNEL: preview
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              UPDATE_INTERVAL: 24
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
            envFrom:
            - secretRef:
                name: tachidesk-secret
            resources:
              requests:
                cpu: 25m
                memory: 500Mi
              limits:
                memory: 1500Mi
            securityContext:
              seLinuxOptions:
                user: system_u
                role: system_r
                type: container_t
                level: s0:c123,c456
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 4567
    ingress:
      main:
        enabled: true
        className: nginx-public
        annotations:
          homelab/public: "true"
          external-dns.alpha.kubernetes.io/hostname: tachidesk.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${DOMAIN}
        hosts:
        - host: tachidesk.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
        globalMounts:
        - path: /home/suwayomi/.local/share/Tachidesk
      tachidesk:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        globalMounts:
        - path: /home/suwayomi/.local/share/Tachidesk/downloads
