---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: torrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      annotations:
        backup.velero.io/backup-volumes-excludes: downloads
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        sysctls:
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
        - name: net.ipv6.conf.default.disable_ipv6
          value: "1"
    controllers:
      main:
        containers:
          main:
            dependsOn: gluetun
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.4
            env:
              QBT_BitTorrent__Session__DefaultSavePath: /downloads/complete
              QBT_BitTorrent__Session__DiskIOReadMode: DisableOSCache
              QBT_BitTorrent__Session__DiskIOType: Posix
              QBT_BitTorrent__Session__DiskIOWriteMode: DisableOSCache
              QBT_BitTorrent__Session__GlobalDlSpeedLimit: "62500"
              QBT_BitTorrent__Session__GlobalMaxRatio: "10"
              QBT_BitTorrent__Session__GlobalUPSpeedLimit: "1000"
              QBT_BitTorrent__Session__MaxActiveDownloads: "10"
              QBT_BitTorrent__Session__MaxActiveTorrents: "20"
              QBT_BitTorrent__Session__MaxActiveUploads: "10"
              QBT_BitTorrent__Session__TempPath: /downloads/incomplete
              QBT_BitTorrent__Session__TempPathEnabled: "true"
              QBT_BitTorrent__Session__TorrentExportDirectory: /downloads/torrent
              QBT_Network__PortForwardingEnabled: "false"
              QBT_Preferences__WebUI__AlternativeUIEnabled: "true"
              QBT_Preferences__WebUI__RootFolder: /shared/vuetorrent
              QBT_Preferences__WebUI__UseUPnP: "false"
            envFrom:
            - secretRef:
                name: torrent-secret
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              seLinuxOptions:
                user: system_u
                role: system_r
                type: container_t
                level: s0:c123,c456
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              HEALTH_VPN_DURATION_INITIAL: 120s
            envFrom:
            - secretRef:
                name: torrent-secret
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                add:
                - NET_ADMIN
              seLinuxOptions:
                user: system_u
                role: system_r
                type: container_t
                level: s0:c123,c456
        initContainers:
          custom-webui:
            image:
              repository: docker.io/curlimages/curl
              tag: 8.12.1
            command:
            - "/bin/sh"
            - "-c"
            - "cd /shared && curl -o- -sL https://github.com/VueTorrent/VueTorrent/releases/download/v2.12.0/vuetorrent.zip | unzip -"
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
      downloads:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
      shared:
        type: emptyDir
