---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  chart:
    spec:
      chart: k8up
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: k8up-io
        namespace: flux-system
  interval: 10m0s
  values:
    registry: ghcr.io
    repository: k8up-io/k8up
    tag: v2.10.0
    timezone: America/Los_Angeles
    k8up:
      envVars:
      - name: K8UP_DEBUG
        value: "true"
