---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopia
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: docker.io/kopia/kopia
              tag: 0.19.0
            envFrom:
            - secretRef:
                name: kopia-secret
            args:
            - server
            - start
            - --insecure
            - --address=0.0.0.0:51515
            - --override-username=jerry@k3s
            - --server-username=jerry@k3s
    persistence:
      backup:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        globalMounts:
        - path: /app/backup
          readOnly: true
      config:
        enabled: true
        type: secret
        name: kopia-repository-config
        globalMounts:
        - path: /app/config/repository.config
          subPath: repository.config
          readOnly: true
