---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kopia
resources:
- namespace.yaml
- secret.sops.yaml
- repository-config.sops.yaml
- helmrelease.yaml
- networkpolicy.yaml
components:
- ../../../components/netpol/base
