---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-anubis
spec:
  releaseName: ingress-anubis
  chartRef:
    kind: OCIRepository
    name: ingress-anubis
    namespace: flux-system
  interval: 10m0s
  values:
    config:
      INGRESS_CLASS_NAME: anubis
      WRAPPED_INGRESS_CLASS_NAME: nginx
