---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 10m0s
  values:
    env:
      REDIS_HOSTNAME: immich-keydb-headless
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-keydb-secret
            key: password
    envFrom:
    - secretRef:
        name: immich-secret
    podAnnotations:
      backup.velero.io/backup-volumes-excludes: library
    image:
      tag: v1.128.0
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
    postgresql:
      enabled: false
    redis:
      enabled: false
    server:
      enabled: true
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      ingress:
        main:
          enabled: true
          ingressClassName: nginx-public
          annotations:
            homelab/public: "true"
            external-dns.alpha.kubernetes.io/hostname: photos.${DOMAIN}
            external-dns.alpha.kubernetes.io/target: ${DOMAIN}
            nginx.ingress.kubernetes.io/proxy-body-size: 10G
            nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
          hosts:
          - host: photos.${DOMAIN}
            paths:
            - path: "/"
        immich:
          enabled: true
          ingressClassName: nginx-public
          annotations:
            homelab/public: "true"
            external-dns.alpha.kubernetes.io/hostname: immich.${DOMAIN}
            external-dns.alpha.kubernetes.io/target: ${DOMAIN}
            nginx.ingress.kubernetes.io/permanent-redirect: "https://photos.${DOMAIN}$request_uri"
          hosts:
          - host: immich.${DOMAIN}
            paths:
            - path: "/"
    machine-learning:
      enabled: true
      podSecurityContext:
        seLinuxOptions:
          user: system_u
          role: system_r
          type: container_t
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: pvc
          accessMode: ReadWriteOnce
