---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: immich-postgres-cluster
  annotations:
    k8up.io/backup: "false"
spec:
  dockerImage: registry.wuhoo.xyz/jerry/spilo-pgvecto.rs:spilo-3.3-p2-pgvectors-0.3.0
  teamId: "immich"
  volume:
    size: 30Gi
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: "1"
      memory: 1Gi
  numberOfInstances: 1
  users:
    # database owner
    immich:
    - superuser
    - createdb
  databases:
    immich: immich
  postgresql:
    version: "15"
