---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scribe
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        annotations:
          keel.sh/policy: force
          keel.sh/trigger: poll
          keel.sh/match-tag: "true"
          keel.sh/pollSchedule: "@every 240m"
        containers:
          main:
            image:
              repository: registry.wuhoo.xyz/jerry/scribe-docker
              tag: latest
            env:
              APP_DOMAIN: https://scribe.${DOMAIN}
              LUCKY_ENV: production
              PORT: "8080"
              SCRIBE_HOST: "0.0.0.0"
            envFrom:
            - secretRef:
                name: scribe-config
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          homelab/public: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: scribe.${DOMAIN}
          external-dns.alpha.kubernetes.io/target: hetzner.${DOMAIN}
        hosts:
        - host: scribe.${DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: *port
        tls:
        - hosts:
          - scribe.${DOMAIN}
          secretName: scribe-cert
