---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-spilo-wal-backup
spec:
  podSelector:
    matchLabels:
      application: spilo
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: ${S3_CIDR}
    ports:
    - port: 443
      protocol: TCP
