---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k3s-notifier
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: registry.wuhoo.xyz/jerry/k3s-notifier
              tag: v0.1.1
            env:
              NTFY_URL: https://ntfy.${DOMAIN}
            envFrom:
            - secretRef:
                name: k3s-notifier-secret
