---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: privatebin
  namespace: privatebin
spec:
  chart:
    spec:
      chart: privatebin
      sourceRef:
        kind: HelmRepository
        name: privatebin
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: privatebin-config
    valuesKey: values.yaml
  values:
    replicaCount: 3
    image:
      repository: docker.io/privatebin/pdo
      tag: 2.0.3
    ingress:
      enabled: true
      className: nginx-public
      annotations:
        homelab/public: "true"
        external-dns.alpha.kubernetes.io/hostname: paste.${DOMAIN}
        external-dns.alpha.kubernetes.io/target: ${DOMAIN}
      hosts:
      - host: paste.${DOMAIN}
        paths:
        - path: /
          pathType: Prefix
    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 82
      fsGroup: 82
    controller:
      kind: Deployment
      pvc:
        requests: 5Gi
        accessModes: ReadWriteMany
        storageClass: ceph-cephfs-ssd-sc
        emptyDir: false
